# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

gems:             [jekyll-paginate, jekyll-gist]

# Setup
title:            RoboComp
tagline:          ''
description:      'A simple robotics framework.'
url:              http://robocomp.github.io
baseurl:          /website

author:
  name:           'RoboComp'
  url:            github.com/robocomp

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/robocomp

theme: jekyll-theme-time-machine